# Generated by Django 5.1.1 on 2024-12-11 08:21

import django.db.models.deletion
import storages.backends.s3
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.CharField(blank=True, null=True)),
                ('price', models.IntegerField(default=0)),
                ('is_favourite', models.BooleanField(default=False)),
                ('in_basket', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ingredients',
            },
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('salad', 'Салат'), ('dessert', 'Десерт')], max_length=20)),
                ('cooking_time', models.PositiveIntegerField(default=30, help_text='Время приготовления в минутах')),
                ('calories', models.PositiveIntegerField(default=200, help_text='Калорийность')),
                ('cooking_level', models.CharField(choices=[('easy', 'Легкая'), ('medium', 'Средняя'), ('hard', 'Сложная')], max_length=10)),
                ('description', models.TextField()),
                ('preparation', models.TextField(help_text='Шаги приготовления')),
                ('image', models.CharField(max_length=100)),
                ('is_favourite', models.BooleanField(default=False)),
                ('in_basket', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'recipes',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(help_text='Количество (граммы, штуки и т.д.)', max_length=50)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='api.recipes')),
            ],
            options={
                'db_table': 'recipe_products',
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
    ]
